### ISSUE TITLE
Missing librairy in the requirements.txt

### ISSUE THREAD

**Issue by AndreT4** [jeremyk6/crossroadsdescriber#3]
Hi @jeremyk6,

It looks like there is an import missing in the requirements.txt file as I get the following message error during the install of the dependencies : 

`
ModuleNotFoundError: No module named 'scipy'
`

Otherwise, the tool looks nice.

**Comment by jeremyk6** [comment]
Fixed in https://github.com/jeremyk6/crossroadsdescriber/commit/9653ededaa166cfc0f2296b47a836c91da532c02 . Thank you @AndreT4 😃 !
